---
title: "公衆衛生学実習 <br> .med[参考資料]"
author: 
    Chaochen Wang | 王　超辰 <br>
    公衆衛生学講座
date: "2020-09-30, 2020-10-07"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      countdown: 60000
      highlightStyle: github
      highlightLines: true
      highlightSpans: true
      countIncrementalSlides: false
      ratio: 4:3 #16:9
editor_options: 
  chunk_output_type: console
---

class: middle

<!-- # [資料リンク](https://github.com/winterwang/Epi2020/raw/master/EZRintro/intro.pdf) -->


```{r include=FALSE}
options(digits=3)
```



## 問題

12）新開発されたこの新型ウイルス胃腸炎感染症の検査方法を、地域住民の1000名に対して実施した。この検査の感度は60％、特異度は98％であった。この新型ウイルス胃腸炎の検査前有病率は4％と推定される。

この新しく開発された検査法で陽性と出た時の有病確率を求めよ。

（グラフ法またはEZRで計算せよ）

---
class: midde

## 回答


.small[
- $P(D) = 0.04; P(+ve | D) = 0.60;  P(-ve | \bar{D})=0.98$

$$
\begin{aligned}
P(D | +ve) & = \frac{P(+ve | D) P(D)}{P(D)P(+ve | D) +  [1 - P(D)][1 - P(-ve | \bar{D})] }\\
& = \frac{0.60 \times 0.04}{0.60 \times 0.04 + (1 - 0.04) \times (1 - 0.98) } \\
& = 55.6\% 
\end{aligned}
$$
```{r}
(0.60 * 0.04) / (0.60 * 0.04 + (1 - 0.04) * (1 - 0.98))
```

]

---
class: middle

.small[
```
epi.tests(.Table, conf.level = 0.95)
              Disease positive Disease negative Total
Test positive               24               19    43
Test negative               16              941   957
Total                       40              960  1000

 Point estimates and 95 % CIs:
---------------------------------------------------------
                                    Estimation Lower CI Upper CI
Apparent prevalence                      0.043    0.031    0.057
True prevalence                          0.040    0.029    0.054
Sensitivity                              0.600    0.433    0.751
Specificity                              0.980    0.969    0.988
*Positive predictive value                0.558    0.399    0.709
Negative predictive value                0.983    0.973    0.990
Diagnstic accuracy                       0.965    0.952    0.976
Likelihood ratio of a positive test     30.316   18.167   50.589
Likelihood ratio of a negative test      0.408    0.279    0.597
---------------------------------------------------------
```
]


---

.med[
```
              Disease positive Disease negative  Total
Test positive               24             19.2   43.2
Test negative               16            940.8  956.8
Total                       40            960.0 1000.0

 Point estimates and 95 % CIs:
---------------------------------------------------------
                                    Estimation Lower CI Upper CI
Apparent prevalence                      0.043    0.031    0.058
True prevalence                          0.040    0.029    0.054
Sensitivity                              0.600    0.433    0.751
Specificity                              0.980    0.969    0.988
*Positive predictive value                0.556    0.397    0.707
Negative predictive value                0.983    0.973    0.990
Diagnstic accuracy                       0.965    0.951    0.975
Likelihood ratio of a positive test     30.000   18.015   49.959
Likelihood ratio of a negative test      0.408    0.279    0.597
---------------------------------------------------------
```
]
